version: "3"
services:
    redis-master:
        image: redis
        container_name: redis-master
        restart: always
        ports:
            - 6384:6379
        volumes:
            - ./redis-data/master:/data
        command: ["redis-server", "--appendonly", "yes", "--requirepass", "123456"]

    redis-slave:
        image: redis
        container_name: redis-slave
        restart: always
        ports:
            - 6385:6379
        volumes:
            - ./redis-data/slave:/data
        command: ["redis-server", "--slaveof", "redis-master", "6379", "--masterauth", "123456", "--requirepass", "123456"]

    redis-sentinel1:
        image: redis:latest
        container_name: redis-sentinel1
        depends_on:
            - redis-master
        ports:
            - 26384:26379
        command: >
            sh -c 'redis-sentinel /usr/local/etc/sentinel.conf'
        links:
            - redis-master
        volumes:
            - ./sentinel1.conf:/usr/local/etc/sentinel.conf


    redis-sentinel2:
        image: redis:latest
        container_name: redis-sentinel2
        depends_on:
            - redis-master
        ports:
            - 26385:26379
        command: >
            sh -c 'redis-sentinel /usr/local/etc/sentinel.conf'
        links:
            - redis-master
        volumes:
            - ./sentinel2.conf:/usr/local/etc/sentinel.conf


    redis-sentinel3:
        image: redis:latest
        container_name: redis-sentinel3
        depends_on:
            - redis-master
        ports:
            - 26386:26379
        command: >
            sh -c 'redis-sentinel /usr/local/etc/sentinel.conf'
        links:
            - redis-master
        volumes:
            - ./sentinel3.conf:/usr/local/etc/sentinel.conf

